#!/bin/sh
#
# Installation script for assemblyToNib
#
# 1) cp Configuration.default Configuration
# 2) Install
###########################################################################
#
#  Purpose:  Checks to see if Configured directories exist, creates output
#	     dirs if they don't exist. 
#  Inputs:
#
#      - Configuration file
#
#  Outputs:  None
#
#  Exit Codes:
#
#      0 = Successful completion
#      1 = An error occurred
###########################################################################
usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${usage}"
    installFailed
fi

#
# Make sure config file exists and source it
#

cd `dirname $0`
CONFIG="./Configuration"

if [ -r ${CONFIG} ]
then
    echo "Source ${CONFIG}"
    . ${CONFIG}
else
    echo "Cannot source configuration file: ${CONFIG}"
    installFailed
fi


# make sure ${INPUTDIR} exists
if [ ! -d ${INPUTDIR} ]
then
    echo "${INPUTDIR} does not exist, please check Configuration"
    installFailed
fi

# make NIB_OUTPUTDIR if it doesn't exist
if [ ! -d ${NIB_OUTPUTDIR} ]
then
    mkdir -p ${NIB_OUTPUTDIR} >/dev/null 2>&1
            if [ $? -eq 0 ]
            then
                  echo "Directory created: ${NIB_OUTPUTDIR}"
            else
                  echo "Cannot create directory: ${NIB_OUTPUTDIR}"
		  installFailed
            fi
            chmod -f 755 ${NIB_OUTPUTDIR}
        else
            echo "Directory already exists: ${NIB_OUTPUTDIR}"
fi

# make FA_OUTPUTDIR if it doesn't exist
if [ ! -d ${FA_OUTPUTDIR} ]
then
    mkdir -p ${FA_OUTPUTDIR} >/dev/null 2>&1
            if [ $? -eq 0 ]
            then
                  echo "Directory created: ${FA_OUTPUTDIR}"
            else
                  echo "Cannot create directory: ${FA_OUTPUTDIR}"
                  installFailed
            fi
            chmod -f 755 ${FA_OUTPUTDIR}
        else
            echo "Directory already exists: ${FA_OUTPUTDIR}"
fi

