#!/bin/sh
#  $Header
#  $Name
#
# Install
# cp Configuration.default Configuration
# ./Install
###########################################################################
#
#  Purpose:  Checks to see if Configured directories exist
#  Inputs:
#
#      - Configuration file
#
#  Outputs:  None
#
#  Exit Codes:
#
#      0 = Successful completion
#      1 = An error occurred
###########################################################################

CONFIG="./Configuration"

cd `dirname $0`

# source Configuration
. $CONFIG

# make sure ${INPUTDIR} exists
if [ ! -d ${INPUTDIR} ]
then
    echo "${INPUTDIR} does not exist, please check Configuration"
    exit 1
fi

# make NIB_OUTPUTDIR if it doesn't exist
if [ ! -d ${NIB_OUTPUTDIR} ]
then
    mkdir -p ${NIB_OUTPUTDIR} >/dev/null 2>&1
            if [ $? -eq 0 ]
            then
                  echo "Directory created: ${NIB_OUTPUTDIR}"
            else
                  echo "Cannot create directory: ${NIB_OUTPUTDIR}"
		  exit 1
            fi
            chmod -f 755 ${NIB_OUTPUTDIR}
        else
            echo "Directory already exists: ${NIB_OUTPUTDIR}"
fi

# make FA_OUTPUTDIR if it doesn't exist
if [ ! -d ${FA_OUTPUTDIR} ]
then
    mkdir -p ${FA_OUTPUTDIR} >/dev/null 2>&1
            if [ $? -eq 0 ]
            then
                  echo "Directory created: ${FA_OUTPUTDIR}"
            else
                  echo "Cannot create directory: ${FA_OUTPUTDIR}"
                  exit 1
            fi
            chmod -f 755 ${FA_OUTPUTDIR}
        else
            echo "Directory already exists: ${FA_OUTPUTDIR}"
fi

